services:
  lambda:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    env_file:
      - .env
    depends_on:
      localstack:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_AVAILABLE_MODELS: ${REACT_APP_AVAILABLE_MODELS}
        REACT_APP_MODEL_BUCKET: ${REACT_APP_MODEL_BUCKET}
        REACT_APP_AWS_ACCESS_KEY_ID: ${REACT_APP_AWS_ACCESS_KEY_ID}
        REACT_APP_AWS_SECRET_ACCESS_KEY: ${REACT_APP_AWS_SECRET_ACCESS_KEY}
        REACT_APP_AWS_ENDPOINT_URL: ${REACT_APP_AWS_ENDPOINT_URL}
        REACT_APP_AWS_REGION: ${REACT_APP_AWS_REGION}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_AVAILABLE_MODELS=${REACT_APP_AVAILABLE_MODELS}
      - REACT_APP_MODEL_BUCKET=${REACT_APP_MODEL_BUCKET}
      - REACT_APP_AWS_ACCESS_KEY_ID=${REACT_APP_AWS_ACCESS_KEY_ID}
      - REACT_APP_AWS_SECRET_ACCESS_KEY=${REACT_APP_AWS_SECRET_ACCESS_KEY}
      - REACT_APP_AWS_ENDPOINT_URL=${REACT_APP_AWS_ENDPOINT_URL}
      - REACT_APP_AWS_REGION=${REACT_APP_AWS_REGION}
    env_file:
      - .env
    depends_on:
      - lambda
      - localstack

  localstack:
    image: localstack/localstack:2.3
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,lambda
      - DEBUG=1
      - PERSISTENCE=1
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - HOSTNAME_EXTERNAL=localstack
      - EAGER_SERVICE_LOADING=1
      - START_WEB=0
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./backend/models:/tmp/models"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  localstack_data:
